from __future__ import annotations

import os
from copy import deepcopy
from datetime import datetime, timezone
from typing import Any

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

ROLE_DEFAULTS: dict[str, Any] = {
    "spec": "",
    "name": "",
    "description": "",
    "personality": "",
    "first_mes": "",
    "avatar": "",
    "mes_example": "",
    "scenario": "",
    "creator_notes": "",
    "system_prompt": "",
    "post_history_instructions": "",
    "alternate_greetings": [],
    "tags": [],
}

PRESET_DEFAULTS: dict[str, Any] = {
    "temperature": 0.75,
    "frequency_penalty": 0.8,
    "presence_penalty": 0.8,
    "top_p": 0.99,
    "top_k": 75,
    "top_a": 0,
    "min_p": 0.1,
    "repetition_penalty": 1.1,
    "names_in_completion": True,
    "main_prompt": "",
    "impersonation_prompt": "",
    "assistant_prefill": "",
    "jailbreak_prompt": "",
}

ENTRY_DEFAULTS: dict[str, Any] = {
    "uid": 0,
    "key": [],
    "keysecondary": [],
    "comment": "",
    "content": "",
    "order": 100,
}

LOREBOOK_DEFAULTS: dict[str, Any] = {
    "name": "",
    "description": "",
    "scan_depth": 50,
    "token_budget": 500,
    "entries": {},
}


def _coerce_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return int(text)
        except ValueError:
            return None
    return None


def _coerce_float(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return float(text)
        except ValueError:
            return None
    return None


def _coerce_bool(value: Any) -> bool | None:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        text = value.strip().lower()
        if text in {"true", "1", "yes", "y"}:
            return True
        if text in {"false", "0", "no", "n"}:
            return False
    return None


def _coerce_string_list(value: Any) -> list[str] | None:
    if isinstance(value, list):
        return [str(item) for item in value if item is not None]
    if isinstance(value, str):
        return [part.strip() for part in value.split(",") if part.strip()]
    return None


def _coerce_by_default(value: Any, default: Any) -> Any:
    if isinstance(default, bool):
        return _coerce_bool(value) if _coerce_bool(value) is not None else deepcopy(default)
    if isinstance(default, int) and not isinstance(default, bool):
        return _coerce_int(value) if _coerce_int(value) is not None else deepcopy(default)
    if isinstance(default, float):
        return _coerce_float(value) if _coerce_float(value) is not None else deepcopy(default)
    if isinstance(default, str):
        return value if isinstance(value, str) else deepcopy(default)
    if isinstance(default, list):
        return _coerce_string_list(value) if _coerce_string_list(value) is not None else deepcopy(default)
    if isinstance(default, dict):
        return deepcopy(value) if isinstance(value, dict) else deepcopy(default)
    return deepcopy(value)


DATABASE_URL = (
    os.getenv("XTPLAY_DATABASE_URL")
    or os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_DSN")
    or "postgresql://postgres:root@localhost:5432/xtplay"
)

CONTENT_TABLES = {"roles", "presets", "entries", "lorebooks"}
PROMPT_KEYS = {"key", "title", "category", "description", "content"}

SCHEMA_SQL = """
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null,
  password text not null,
  email text not null default '',
  role text not null default 'normal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table users add column if not exists role text not null default 'normal';

create unique index if not exists users_username_lower_uidx on users (lower(username));

insert into users (username, password, email, role)
select 'super_admin', 'super_admin123', 'super@xtplay.com', 'super_admin'
where not exists (select 1 from users where lower(username) = 'super_admin');
update users set role = 'admin' where username = 'admin' and role = 'normal';

create table if not exists roles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists presets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lorebooks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists stories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists story_rounds (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  story_id bigint not null references stories(id) on delete cascade,
  position integer not null default 0,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists prompts (
  key text primary key,
  title text not null default '',
  category text not null default '',
  description text not null default '',
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists roles_user_id_idx on roles (user_id);
create index if not exists presets_user_id_idx on presets (user_id);
create index if not exists entries_user_id_idx on entries (user_id);
create index if not exists lorebooks_user_id_idx on lorebooks (user_id);
create index if not exists stories_user_id_idx on stories (user_id);
create index if not exists story_rounds_user_id_idx on story_rounds (user_id);
create index if not exists story_rounds_story_id_idx on story_rounds (story_id);
create index if not exists story_rounds_story_position_idx on story_rounds (story_id, position, id);
create index if not exists prompts_category_idx on prompts (category);

create table if not exists story_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  story_id bigint not null references stories(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists session_rounds (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  session_id bigint not null references story_sessions(id) on delete cascade,
  position integer not null default 0,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists story_sessions_user_id_idx on story_sessions (user_id);
create index if not exists story_sessions_story_id_idx on story_sessions (story_id);
create index if not exists session_rounds_user_id_idx on session_rounds (user_id);
create index if not exists session_rounds_session_id_idx on session_rounds (session_id);
create index if not exists session_rounds_session_position_idx on session_rounds (session_id, position, id);
"""


def connect() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def init_db() -> None:
    with connect() as conn:
        for statement in SCHEMA_SQL.split(";"):
            sql = statement.strip()
            if sql:
                conn.execute(sql)


def _iso(value: Any) -> str:
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value or "")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _public_user(user: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": int(user["id"]),
        "username": str(user["username"]),
        "email": str(user.get("email", "")),
        "role": str(user.get("role", "normal")),
    }


def _format_output(action: Any, dialogue: Any) -> str:
    parts = []
    action_text = str(action or "").strip()
    dialogue_text = str(dialogue or "").strip()
    if action_text:
        parts.append(action_text)
    if dialogue_text:
        parts.append(f'"{dialogue_text}"')
    return "\n".join(parts)


class PostgresUserStore:
    def list_all(self) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute("select id, username, email, role from users order by id").fetchall()
        return [_public_user(row) for row in rows]

    def get(self, user_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                "select id, username, email, role from users where id = %s",
                (user_id,),
            ).fetchone()
        return _public_user(row) if row is not None else None

    def get_full(self, user_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                "select id, username, password, email, role from users where id = %s",
                (user_id,),
            ).fetchone()
        return dict(row) if row is not None else None

    def get_by_username(self, username: str) -> dict[str, Any] | None:
        clean_username = username.strip()
        if not clean_username:
            return None
        with connect() as conn:
            row = conn.execute(
                "select id, username, password, email, role from users where lower(username) = lower(%s)",
                (clean_username,),
            ).fetchone()
        return dict(row) if row is not None else None

    def create(self, username: str, password: str, email: str = "") -> dict[str, Any]:
        clean_username = username.strip()
        clean_password = password.strip()
        clean_email = email.strip()
        if not clean_username:
            raise ValueError("用户名不能为空")
        if not clean_password:
            raise ValueError("密码不能为空")
        if self.get_by_username(clean_username) is not None:
            raise ValueError("用户名已存在")

        with connect() as conn:
            row = conn.execute(
                """
                insert into users (username, password, email, role)
                values (%s, %s, %s, %s)
                returning id, username, email, role
                """,
                (clean_username, clean_password, clean_email, "normal"),
            ).fetchone()
        return _public_user(row)

    def authenticate(self, username: str, password: str) -> dict[str, Any] | None:
        user = self.get_by_username(username)
        if user is None or user.get("password") != password:
            return None
        return _public_user(user)

    def update(self, user_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        current = self.get(user_id)
        if current is None:
            return None
        set_clauses = []
        params: list[Any] = []
        if "username" in payload and payload["username"] is not None:
            clean_username = str(payload["username"]).strip()
            if clean_username and clean_username != current["username"]:
                existing = self.get_by_username(clean_username)
                if existing is not None and int(existing["id"]) != user_id:
                    raise ValueError("用户名已存在")
            set_clauses.append("username = %s")
            params.append(clean_username)
        if "email" in payload and payload["email"] is not None:
            set_clauses.append("email = %s")
            params.append(str(payload["email"]).strip())
        if "password" in payload and payload["password"] is not None:
            clean_password = str(payload["password"]).strip()
            if clean_password:
                set_clauses.append("password = %s")
                params.append(clean_password)
        if not set_clauses:
            return current
        set_clauses.append("updated_at = now()")
        params.append(user_id)
        with connect() as conn:
            row = conn.execute(
                f"update users set {', '.join(set_clauses)} where id = %s returning id, username, email, role",
                params,
            ).fetchone()
        return _public_user(row) if row is not None else None

    def update_role(self, user_id: int, role: str) -> dict[str, Any] | None:
        if role not in ("normal", "admin", "super_admin"):
            raise ValueError("无效的角色值")
        with connect() as conn:
            row = conn.execute(
                "update users set role = %s, updated_at = now() where id = %s returning id, username, email, role",
                (role, user_id),
            ).fetchone()
        return _public_user(row) if row is not None else None


class PostgresCollection:
    def __init__(
        self,
        table: str,
        defaults: dict[str, Any] | None = None,
        unwrap_data: bool = False,
    ) -> None:
        if table not in CONTENT_TABLES:
            raise ValueError(f"unsupported table: {table}")
        self.table = table
        self.defaults = defaults
        self.unwrap_data = unwrap_data

    def list_all(self, user_id: int) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute(
                f"select id, data from {self.table} where user_id = %s order by id",
                (user_id,),
            ).fetchall()
        return [self._row_to_item(row) for row in rows]

    def get(self, user_id: int, item_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                f"select id, data from {self.table} where id = %s and user_id = %s",
                (item_id, user_id),
            ).fetchone()
        return self._row_to_item(row) if row is not None else None

    def create(self, user_id: int, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._shape_item(payload)
        with connect() as conn:
            row = conn.execute(
                f"insert into {self.table} (user_id, data) values (%s, %s) returning id, data",
                (user_id, Jsonb(data)),
            ).fetchone()
            item = self._row_to_item(row)
            self._save_item_data(conn, int(row["id"]), item)
        return item

    def replace(self, user_id: int, item_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._shape_item(payload)
        with connect() as conn:
            row = conn.execute(
                f"""
                update {self.table}
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), item_id, user_id),
            ).fetchone()
            if row is None:
                return None
            item = self._row_to_item(row)
            self._save_item_data(conn, int(row["id"]), item)
        return item

    def patch(self, user_id: int, item_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get(user_id, item_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        data = self._shape_item(patched)
        data["id"] = item_id
        self._ensure_uid(data)
        with connect() as conn:
            row = conn.execute(
                f"""
                update {self.table}
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(self._data_for_storage(data)), item_id, user_id),
            ).fetchone()
        return self._row_to_item(row) if row is not None else None

    def delete(self, user_id: int, item_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                f"delete from {self.table} where id = %s and user_id = %s",
                (item_id, user_id),
            )
        return cursor.rowcount > 0

    def _save_item_data(self, conn: psycopg.Connection, item_id: int, item: dict[str, Any]) -> None:
        conn.execute(
            f"update {self.table} set data = %s, updated_at = now() where id = %s",
            (Jsonb(self._data_for_storage(item)), item_id),
        )

    def _row_to_item(self, row: dict[str, Any]) -> dict[str, Any]:
        item = self._shape_item(dict(row.get("data") or {}))
        item["id"] = int(row["id"])
        self._ensure_uid(item)
        return item

    def _shape_item(self, item: dict[str, Any]) -> dict[str, Any]:
        if self.defaults is None:
            return deepcopy(item)

        source = deepcopy(item)
        if self.unwrap_data and isinstance(source.get("data"), dict):
            source = {"spec": source.get("spec", ""), **source["data"]}

        return {
            key: _coerce_by_default(source[key], default) if key in source else deepcopy(default)
            for key, default in self.defaults.items()
        }

    def _ensure_uid(self, item: dict[str, Any]) -> None:
        if "uid" not in item:
            return
        uid = _coerce_int(item.get("uid"))
        item_id = _coerce_int(item.get("id"))
        if (uid is None or uid <= 0) and item_id is not None:
            item["uid"] = item_id

    def _data_for_storage(self, item: dict[str, Any]) -> dict[str, Any]:
        data = deepcopy(item)
        data.pop("id", None)
        data.pop("created_at", None)
        data.pop("updated_at", None)
        return data


class PostgresLorebookCollection(PostgresCollection):
    def list_entries(self, user_id: int, lorebook_id: int) -> list[dict[str, Any]] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        entries = self._normalize_entries(lorebook.get("entries"))
        return [deepcopy(entry) for _, entry in entries]

    def get_entry(self, user_id: int, lorebook_id: int, entry_id: int) -> dict[str, Any] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        for _, entry in self._normalize_entries(lorebook.get("entries")):
            if self._entry_id(entry) == entry_id:
                return deepcopy(entry)
        return None

    def create_entry(self, user_id: int, lorebook_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        entries = self._normalize_entries(lorebook.get("entries"))
        new_entry = self._prepare_entry_create(payload, entries)
        entries.append((str(self._entry_id(new_entry)), new_entry))
        lorebook["entries"] = {key: entry for key, entry in entries}
        self.replace(user_id, lorebook_id, lorebook)
        return deepcopy(new_entry)

    def replace_entry(
        self,
        user_id: int,
        lorebook_id: int,
        entry_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        return self._mutate_entry(user_id, lorebook_id, payload, "replace", entry_id)

    def patch_entry(
        self,
        user_id: int,
        lorebook_id: int,
        entry_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        return self._mutate_entry(user_id, lorebook_id, payload, "patch", entry_id)

    def delete_entry(self, user_id: int, lorebook_id: int, entry_id: int) -> bool:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return False
        entries = self._normalize_entries(lorebook.get("entries"))
        filtered = [(key, entry) for key, entry in entries if self._entry_id(entry) != entry_id]
        if len(filtered) == len(entries):
            return False
        lorebook["entries"] = {key: entry for key, entry in filtered}
        self.replace(user_id, lorebook_id, lorebook)
        return True

    def _mutate_entry(
        self,
        user_id: int,
        lorebook_id: int,
        payload: dict[str, Any],
        mode: str,
        entry_id: int,
    ) -> dict[str, Any] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        entries = self._normalize_entries(lorebook.get("entries"))
        for index, (key, entry) in enumerate(entries):
            if self._entry_id(entry) != entry_id:
                continue
            if mode == "replace":
                updated = self._prepare_entry_replace(payload, entry_id)
            else:
                updated = self._prepare_entry_patch(entry, payload, entry_id)
            entries[index] = (key, updated)
            lorebook["entries"] = {entry_key: entry_value for entry_key, entry_value in entries}
            self.replace(user_id, lorebook_id, lorebook)
            return deepcopy(updated)
        return None

    def _shape_item(self, item: dict[str, Any]) -> dict[str, Any]:
        shaped = super()._shape_item(item)
        entries = self._normalize_entries(item.get("entries", shaped.get("entries")))
        shaped["entries"] = {key: entry for key, entry in entries}
        return shaped

    def _normalize_entries(self, entries: Any) -> list[tuple[str, dict[str, Any]]]:
        if isinstance(entries, dict):
            source_items = list(entries.items())
        elif isinstance(entries, list):
            source_items = [(str(index + 1), value) for index, value in enumerate(entries)]
        else:
            source_items = []

        normalized: list[tuple[str, dict[str, Any]]] = []
        next_entry_id = self._next_entry_id(source_items)
        for raw_key, raw_entry in source_items:
            if not isinstance(raw_entry, dict):
                continue
            raw_entry_id = self._entry_id(raw_entry)
            raw_uid = _coerce_int(raw_entry.get("uid"))
            key_id = _coerce_int(raw_key)
            entry_id = raw_entry_id if raw_entry_id is not None else raw_uid
            if entry_id is None or entry_id <= 0:
                entry_id = key_id
            if entry_id is None:
                entry_id = next_entry_id
            entry = self._shape_entry(raw_entry)
            entry["id"] = entry_id
            self._ensure_entry_uid(entry, entry_id)
            normalized.append((str(entry_id), entry))
            if entry_id >= next_entry_id:
                next_entry_id = entry_id + 1
        normalized.sort(key=lambda item: self._entry_id(item[1]) or 0)
        return normalized

    def _shape_entry(self, entry: dict[str, Any]) -> dict[str, Any]:
        return {
            key: _coerce_by_default(entry[key], default) if key in entry else deepcopy(default)
            for key, default in ENTRY_DEFAULTS.items()
        }

    def _prepare_entry_create(
        self,
        payload: dict[str, Any],
        entries: list[tuple[str, dict[str, Any]]],
    ) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        entry = self._shape_entry(payload)
        uid = _coerce_int(entry.get("uid"))
        next_entry_id = self._next_entry_id(entries)
        entry_id = uid if uid is not None and uid > 0 else next_entry_id
        entry["id"] = entry_id
        self._ensure_entry_uid(entry, entry_id)
        return entry

    def _prepare_entry_replace(self, payload: dict[str, Any], entry_id: int) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        entry = self._shape_entry(payload)
        entry["id"] = entry_id
        self._ensure_entry_uid(entry, entry_id)
        return entry

    def _prepare_entry_patch(
        self,
        current_entry: dict[str, Any],
        payload: dict[str, Any],
        entry_id: int,
    ) -> dict[str, Any]:
        patched = deepcopy(current_entry)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        entry = self._shape_entry(patched)
        entry["id"] = entry_id
        self._ensure_entry_uid(entry, entry_id)
        return entry

    def _ensure_entry_uid(self, entry: dict[str, Any], entry_id: int) -> None:
        uid = _coerce_int(entry.get("uid"))
        if uid is None or uid <= 0:
            entry["uid"] = entry_id

    def _entry_id(self, entry: dict[str, Any]) -> int | None:
        return _coerce_int(entry.get("id"))

    def _next_entry_id(self, entries: list[tuple[str, dict[str, Any]]]) -> int:
        max_id = 0
        for key, entry in entries:
            if not isinstance(entry, dict):
                continue
            entry_id = self._entry_id(entry)
            if entry_id is None:
                entry_id = _coerce_int(entry.get("uid"))
            if entry_id is None:
                entry_id = _coerce_int(key)
            if entry_id is not None and entry_id > max_id:
                max_id = entry_id
        return max_id + 1


class PostgresPromptStore:
    def list_all(self) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute(
                """
                select key, title, category, description, content, created_at, updated_at
                from prompts
                order by category, key
                """
            ).fetchall()
        return [self._row_to_prompt(row) for row in rows]

    def get(self, key: str) -> dict[str, Any] | None:
        clean_key = key.strip()
        if not clean_key:
            return None
        with connect() as conn:
            row = conn.execute(
                """
                select key, title, category, description, content, created_at, updated_at
                from prompts
                where key = %s
                """,
                (clean_key,),
            ).fetchone()
        return self._row_to_prompt(row) if row is not None else None

    def replace(self, key: str, payload: dict[str, Any]) -> dict[str, Any] | None:
        clean_key = key.strip()
        if not clean_key or self.get(clean_key) is None:
            return None
        data = self._shape_prompt({"key": clean_key, **payload})
        with connect() as conn:
            row = conn.execute(
                """
                update prompts
                set title = %s,
                    category = %s,
                    description = %s,
                    content = %s,
                    updated_at = now()
                where key = %s
                returning key, title, category, description, content, created_at, updated_at
                """,
                (
                    data["title"],
                    data["category"],
                    data["description"],
                    data["content"],
                    clean_key,
                ),
            ).fetchone()
        return self._row_to_prompt(row) if row is not None else None

    def patch(self, key: str, payload: dict[str, Any]) -> dict[str, Any] | None:
        current = self.get(key)
        if current is None:
            return None
        patched = deepcopy(current)
        for field, value in payload.items():
            if field in PROMPT_KEYS and field != "key":
                patched[field] = value
        return self.replace(str(current["key"]), patched)

    def seed_defaults(self, defaults: list[dict[str, str]]) -> None:
        with connect() as conn:
            for item in defaults:
                data = self._shape_prompt(item)
                if not data["key"]:
                    continue
                conn.execute(
                    """
                    insert into prompts (key, title, category, description, content)
                    values (%s, %s, %s, %s, %s)
                    on conflict (key) do nothing
                    """,
                    (
                        data["key"],
                        data["title"],
                        data["category"],
                        data["description"],
                        data["content"],
                    ),
                )

    def _shape_prompt(self, item: dict[str, Any]) -> dict[str, str]:
        return {
            "key": str(item.get("key", "")).strip(),
            "title": str(item.get("title", "")).strip(),
            "category": str(item.get("category", "")).strip(),
            "description": str(item.get("description", "")).strip(),
            "content": str(item.get("content", "")),
        }

    def _row_to_prompt(self, row: dict[str, Any]) -> dict[str, Any]:
        return {
            "key": str(row["key"]),
            "title": str(row.get("title", "")),
            "category": str(row.get("category", "")),
            "description": str(row.get("description", "")),
            "content": str(row.get("content", "")),
            "created_at": _iso(row.get("created_at")),
            "updated_at": _iso(row.get("updated_at")),
        }


def migrate_story_rounds_to_sessions() -> None:
    """One-time migration: create default sessions for stories with old-style rounds."""
    with connect() as conn:
        rows = conn.execute("""
            SELECT DISTINCT s.id, s.user_id, s.data
            FROM stories s
            JOIN story_rounds sr ON sr.story_id = s.id
            WHERE NOT EXISTS (
                SELECT 1 FROM story_sessions ss
                WHERE ss.story_id = s.id AND ss.user_id = s.user_id
            )
        """).fetchall()

        for row in rows:
            story_data = row["data"] or {}
            story_title = str(story_data.get("title", "") or "默认会话")
            session_data = {"title": story_title, "status": "active"}
            session_row = conn.execute(
                """
                insert into story_sessions (user_id, story_id, data)
                values (%s, %s, %s)
                returning id
                """,
                (row["user_id"], row["id"], Jsonb(session_data)),
            ).fetchone()
            session_id = int(session_row["id"])

            rounds = conn.execute(
                """
                select position, data
                from story_rounds
                where story_id = %s and user_id = %s
                order by position, id
                """,
                (row["id"], row["user_id"]),
            ).fetchall()

            for rnd in rounds:
                conn.execute(
                    """
                    insert into session_rounds (user_id, session_id, position, data)
                    values (%s, %s, %s, %s)
                    """,
                    (row["user_id"], session_id, int(rnd["position"]), Jsonb(rnd["data"])),
                )


class PostgresSessionStore:
    def list_by_story(self, user_id: int, story_id: int) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute(
                """
                select id, user_id, story_id, data, created_at, updated_at
                from story_sessions
                where user_id = %s and story_id = %s
                order by id
                """,
                (user_id, story_id),
            ).fetchall()
            return [self._row_to_session(conn, row) for row in rows]

    def get(self, user_id: int, session_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                """
                select id, user_id, story_id, data, created_at, updated_at
                from story_sessions
                where id = %s and user_id = %s
                """,
                (session_id, user_id),
            ).fetchone()
            return self._row_to_session(conn, row) if row is not None else None

    def create(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._session_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                insert into story_sessions (user_id, story_id, data)
                values (%s, %s, %s)
                returning id, user_id, story_id, data, created_at, updated_at
                """,
                (user_id, story_id, Jsonb(data)),
            ).fetchone()
            return self._row_to_session(conn, row)

    def update(self, user_id: int, session_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get(user_id, session_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key not in {"id", "story_id", "created_at", "updated_at", "round"}:
                patched[key] = value
        data = self._session_data_for_storage(patched)
        with connect() as conn:
            row = conn.execute(
                """
                update story_sessions
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, user_id, story_id, data, created_at, updated_at
                """,
                (Jsonb(data), session_id, user_id),
            ).fetchone()
            return self._row_to_session(conn, row) if row is not None else None

    def delete(self, user_id: int, session_id: int) -> bool:
        # session_rounds cascade-deletes via FK
        with connect() as conn:
            cursor = conn.execute(
                "delete from story_sessions where id = %s and user_id = %s",
                (session_id, user_id),
            )
        return cursor.rowcount > 0

    # --- Round CRUD ---

    def list_rounds(self, user_id: int, session_id: int) -> list[dict[str, Any]]:
        with connect() as conn:
            return self._list_rounds(conn, user_id, session_id)

    def get_round(self, user_id: int, session_id: int, round_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                """
                select id, data
                from session_rounds
                where id = %s and session_id = %s and user_id = %s
                """,
                (round_id, session_id, user_id),
            ).fetchone()
        return self._row_to_round(row) if row is not None else None

    def create_round(self, user_id: int, session_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not self._session_exists(user_id, session_id):
            return None
        with connect() as conn:
            position = self._next_round_position(conn, user_id, session_id)
            new_round = self._insert_round(conn, user_id, session_id, payload, position)
            conn.execute(
                "update story_sessions set updated_at = now() where id = %s and user_id = %s",
                (session_id, user_id),
            )
        return new_round

    def replace_round(self, user_id: int, session_id: int, round_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._round_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                update session_rounds
                set data = %s, updated_at = now()
                where id = %s and session_id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), round_id, session_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "update story_sessions set updated_at = now() where id = %s and user_id = %s",
                (session_id, user_id),
            )
        return self._row_to_round(row)

    def patch_round(self, user_id: int, session_id: int, round_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get_round(user_id, session_id, round_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        data = self._round_data_for_storage(patched)
        with connect() as conn:
            row = conn.execute(
                """
                update session_rounds
                set data = %s, updated_at = now()
                where id = %s and session_id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), round_id, session_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "update story_sessions set updated_at = now() where id = %s and user_id = %s",
                (session_id, user_id),
            )
        return self._row_to_round(row)

    def delete_round(self, user_id: int, session_id: int, round_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                """
                delete from session_rounds
                where id = %s and session_id = %s and user_id = %s
                """,
                (round_id, session_id, user_id),
            )
            deleted = cursor.rowcount > 0
            if deleted:
                conn.execute(
                    "update story_sessions set updated_at = now() where id = %s and user_id = %s",
                    (session_id, user_id),
                )
        return deleted

    # --- Internal helpers ---

    def _session_exists(self, user_id: int, session_id: int) -> bool:
        with connect() as conn:
            row = conn.execute(
                "select id from story_sessions where id = %s and user_id = %s",
                (session_id, user_id),
            ).fetchone()
        return row is not None

    def _row_to_session(self, conn: psycopg.Connection, row: dict[str, Any]) -> dict[str, Any]:
        data = dict(row.get("data") or {})
        session: dict[str, Any] = {
            "id": int(row["id"]),
            "story_id": int(row["story_id"]),
            "title": str(data.get("title", "") or ""),
            "status": str(data.get("status", "active") or "active"),
            "round": self._list_rounds(conn, int(row["user_id"]), int(row["id"])),
            "created_at": _iso(row.get("created_at")) or _now_iso(),
            "updated_at": _iso(row.get("updated_at")) or _now_iso(),
        }
        return session

    def _list_rounds(self, conn: psycopg.Connection, user_id: int, session_id: int) -> list[dict[str, Any]]:
        rows = conn.execute(
            """
            select id, data
            from session_rounds
            where user_id = %s and session_id = %s
            order by position, id
            """,
            (user_id, session_id),
        ).fetchall()
        return [self._row_to_round(row) for row in rows]

    def _insert_round(
        self,
        conn: psycopg.Connection,
        user_id: int,
        session_id: int,
        payload: dict[str, Any],
        position: int,
    ) -> dict[str, Any]:
        data = self._round_data_for_storage(payload)
        row = conn.execute(
            """
            insert into session_rounds (user_id, session_id, position, data)
            values (%s, %s, %s, %s)
            returning id, data
            """,
            (user_id, session_id, position, Jsonb(data)),
        ).fetchone()
        return self._row_to_round(row)

    def _next_round_position(self, conn: psycopg.Connection, user_id: int, session_id: int) -> int:
        row = conn.execute(
            """
            select coalesce(max(position), 0) + 1 as next_position
            from session_rounds
            where user_id = %s and session_id = %s
            """,
            (user_id, session_id),
        ).fetchone()
        return int(row["next_position"])

    def _session_data_for_storage(self, payload: dict[str, Any]) -> dict[str, Any]:
        data = deepcopy(payload)
        for key in ("id", "story_id", "created_at", "updated_at", "round"):
            data.pop(key, None)
        return data

    def _round_data_for_storage(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        round_item = deepcopy(payload)
        round_item.pop("id", None)
        self._normalize_round_shape(round_item)
        return round_item

    def _row_to_round(self, row: dict[str, Any]) -> dict[str, Any]:
        round_item = dict(row.get("data") or {})
        round_item["id"] = int(row["id"])
        self._normalize_round_shape(round_item)
        return round_item

    def _normalize_round_shape(self, round_item: dict[str, Any]) -> None:
        round_item.setdefault("scene", "")
        round_item.setdefault("narration", "")
        first = round_item.get("first")
        round_item["first"] = first if first in {"role1", "role2"} else "role1"
        round_item.setdefault("next_scene", "")
        round_item.setdefault("next_narration", "")
        next_first = round_item.get("next_first")
        round_item["next_first"] = next_first if next_first in {"role1", "role2"} else "role1"
        for role_key in ("role1", "role2"):
            action_key = f"{role_key}_action"
            dialogue_key = f"{role_key}_dialogue"
            output_key = f"{role_key}_output"
            round_item.setdefault(action_key, "")
            round_item.setdefault(dialogue_key, "")
            if not round_item.get(output_key):
                round_item[output_key] = _format_output(
                    round_item.get(action_key, ""),
                    round_item.get(dialogue_key, ""),
                )
            elif not round_item.get(action_key) and not round_item.get(dialogue_key):
                round_item[output_key] = str(round_item.get(output_key, ""))


class PostgresStoryCollection:
    def list_all(self, user_id: int) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute(
                """
                select id, user_id, data, created_at, updated_at
                from stories
                where user_id = %s
                order by id
                """,
                (user_id,),
            ).fetchall()
            return [self._row_to_story(row) for row in rows]

    def get(self, user_id: int, story_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                """
                select id, user_id, data, created_at, updated_at
                from stories
                where id = %s and user_id = %s
                """,
                (story_id, user_id),
            ).fetchone()
            return self._row_to_story(row) if row is not None else None

    def create(self, user_id: int, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._story_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                insert into stories (user_id, data)
                values (%s, %s)
                returning id, user_id, data, created_at, updated_at
                """,
                (user_id, Jsonb(data)),
            ).fetchone()
            return self._row_to_story(row)

    def replace(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._story_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                update stories
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, user_id, data, created_at, updated_at
                """,
                (Jsonb(data), story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            return self._row_to_story(row)

    def patch(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get(user_id, story_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key not in {"id", "created_at", "updated_at"}:
                patched[key] = value
        data = self._story_data_for_storage(patched)
        with connect() as conn:
            row = conn.execute(
                """
                update stories
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, user_id, data, created_at, updated_at
                """,
                (Jsonb(data), story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            return self._row_to_story(row)

    def delete(self, user_id: int, story_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                "delete from stories where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return cursor.rowcount > 0

    def list_rounds(self, user_id: int, story_id: int) -> list[dict[str, Any]] | None:
        if not self._story_exists(user_id, story_id):
            return None
        with connect() as conn:
            return self._list_rounds(conn, user_id, story_id)

    def get_round(self, user_id: int, story_id: int, round_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                """
                select id, data
                from story_rounds
                where id = %s and story_id = %s and user_id = %s
                """,
                (round_id, story_id, user_id),
            ).fetchone()
        return self._row_to_round(row) if row is not None else None

    def create_round(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not self._story_exists(user_id, story_id):
            return None
        with connect() as conn:
            position = self._next_round_position(conn, user_id, story_id)
            round_item = self._insert_round(conn, user_id, story_id, payload, position)
            conn.execute(
                "update stories set updated_at = now() where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return round_item

    def replace_round(
        self,
        user_id: int,
        story_id: int,
        round_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._round_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                update story_rounds
                set data = %s, updated_at = now()
                where id = %s and story_id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), round_id, story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "update stories set updated_at = now() where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return self._row_to_round(row)

    def patch_round(
        self,
        user_id: int,
        story_id: int,
        round_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get_round(user_id, story_id, round_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        data = self._round_data_for_storage(patched)
        with connect() as conn:
            row = conn.execute(
                """
                update story_rounds
                set data = %s, updated_at = now()
                where id = %s and story_id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), round_id, story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "update stories set updated_at = now() where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return self._row_to_round(row)

    def delete_round(self, user_id: int, story_id: int, round_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                """
                delete from story_rounds
                where id = %s and story_id = %s and user_id = %s
                """,
                (round_id, story_id, user_id),
            )
            deleted = cursor.rowcount > 0
            if deleted:
                conn.execute(
                    "update stories set updated_at = now() where id = %s and user_id = %s",
                    (story_id, user_id),
                )
        return deleted

    def _story_exists(self, user_id: int, story_id: int) -> bool:
        with connect() as conn:
            row = conn.execute(
                "select id from stories where id = %s and user_id = %s",
                (story_id, user_id),
            ).fetchone()
        return row is not None

    def _row_to_story(self, row: dict[str, Any]) -> dict[str, Any]:
        story = dict(row.get("data") or {})
        story["id"] = int(row["id"])
        story["created_at"] = _iso(row.get("created_at")) or _now_iso()
        story["updated_at"] = _iso(row.get("updated_at")) or story["created_at"]
        return story

    def _list_rounds(self, conn: psycopg.Connection, user_id: int, story_id: int) -> list[dict[str, Any]]:
        rows = conn.execute(
            """
            select id, data
            from story_rounds
            where user_id = %s and story_id = %s
            order by position, id
            """,
            (user_id, story_id),
        ).fetchall()
        return [self._row_to_round(row) for row in rows]

    def _insert_round(
        self,
        conn: psycopg.Connection,
        user_id: int,
        story_id: int,
        payload: dict[str, Any],
        position: int,
    ) -> dict[str, Any]:
        data = self._round_data_for_storage(payload)
        row = conn.execute(
            """
            insert into story_rounds (user_id, story_id, position, data)
            values (%s, %s, %s, %s)
            returning id, data
            """,
            (user_id, story_id, position, Jsonb(data)),
        ).fetchone()
        return self._row_to_round(row)

    def _next_round_position(self, conn: psycopg.Connection, user_id: int, story_id: int) -> int:
        row = conn.execute(
            """
            select coalesce(max(position), 0) + 1 as next_position
            from story_rounds
            where user_id = %s and story_id = %s
            """,
            (user_id, story_id),
        ).fetchone()
        return int(row["next_position"])

    def _story_data_for_storage(self, payload: dict[str, Any]) -> dict[str, Any]:
        data = deepcopy(payload)
        for key in ("id", "created_at", "updated_at", "round"):
            data.pop(key, None)
        return data

    def _round_data_for_storage(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        round_item = deepcopy(payload)
        round_item.pop("id", None)
        self._normalize_round_shape(round_item)
        return round_item

    def _row_to_round(self, row: dict[str, Any]) -> dict[str, Any]:
        round_item = dict(row.get("data") or {})
        round_item["id"] = int(row["id"])
        self._normalize_round_shape(round_item)
        return round_item

    def _normalize_rounds(self, rounds: Any) -> list[dict[str, Any]]:
        if not isinstance(rounds, list):
            return []
        normalized = []
        next_id = self._next_round_id(rounds)
        for raw_round in rounds:
            if not isinstance(raw_round, dict):
                continue
            round_item = deepcopy(raw_round)
            round_id = _coerce_int(round_item.get("id"))
            if round_id is None or round_id <= 0:
                round_item["id"] = next_id
                next_id += 1
            else:
                round_item["id"] = round_id
            self._normalize_round_shape(round_item)
            normalized.append(round_item)
        return normalized

    def _next_round_id(self, rounds: Any) -> int:
        if not isinstance(rounds, list):
            return 1
        max_id = 0
        for round_item in rounds:
            if not isinstance(round_item, dict):
                continue
            round_id = _coerce_int(round_item.get("id"))
            if round_id is not None and round_id > max_id:
                max_id = round_id
        return max_id + 1

    def _normalize_round_shape(self, round_item: dict[str, Any]) -> None:
        round_item.setdefault("scene", "")
        round_item.setdefault("narration", "")
        first = round_item.get("first")
        round_item["first"] = first if first in {"role1", "role2"} else "role1"
        round_item.setdefault("next_scene", "")
        round_item.setdefault("next_narration", "")
        next_first = round_item.get("next_first")
        round_item["next_first"] = next_first if next_first in {"role1", "role2"} else "role1"
        for role_key in ("role1", "role2"):
            action_key = f"{role_key}_action"
            dialogue_key = f"{role_key}_dialogue"
            output_key = f"{role_key}_output"
            round_item.setdefault(action_key, "")
            round_item.setdefault(dialogue_key, "")
            if not round_item.get(output_key):
                round_item[output_key] = _format_output(
                    round_item.get(action_key, ""),
                    round_item.get(dialogue_key, ""),
                )
            elif not round_item.get(action_key) and not round_item.get(dialogue_key):
                round_item[output_key] = str(round_item.get(output_key, ""))
