from __future__ import annotations

import json
import os
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

from app.db.json_store import (
    ENTRY_DEFAULTS,
    _coerce_by_default,
    _coerce_int,
)


DATABASE_URL = (
    os.getenv("XTPLAY_DATABASE_URL")
    or os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_DSN")
    or "postgresql://postgres:root@localhost:5432/xtplay"
)

CONTENT_TABLES = {"roles", "presets", "entries", "lorebooks"}

SCHEMA_SQL = """
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null,
  password text not null,
  email text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists users_username_lower_uidx on users (lower(username));

create table if not exists roles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists presets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lorebooks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists stories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists story_rounds (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  story_id bigint not null references stories(id) on delete cascade,
  position integer not null default 0,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists roles_user_id_idx on roles (user_id);
create index if not exists presets_user_id_idx on presets (user_id);
create index if not exists entries_user_id_idx on entries (user_id);
create index if not exists lorebooks_user_id_idx on lorebooks (user_id);
create index if not exists stories_user_id_idx on stories (user_id);
create index if not exists story_rounds_user_id_idx on story_rounds (user_id);
create index if not exists story_rounds_story_id_idx on story_rounds (story_id);
create index if not exists story_rounds_story_position_idx on story_rounds (story_id, position, id);
"""


def connect() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def init_db() -> None:
    with connect() as conn:
        for statement in SCHEMA_SQL.split(";"):
            sql = statement.strip()
            if sql:
                conn.execute(sql)


def _iso(value: Any) -> str:
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value or "")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _read_json(path: Path) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def _public_user(user: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": int(user["id"]),
        "username": str(user["username"]),
        "email": str(user.get("email", "")),
    }


def _format_output(action: Any, dialogue: Any) -> str:
    parts = []
    action_text = str(action or "").strip()
    dialogue_text = str(dialogue or "").strip()
    if action_text:
        parts.append(action_text)
    if dialogue_text:
        parts.append(f'"{dialogue_text}"')
    return "\n".join(parts)


class PostgresUserStore:
    def list_all(self) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute("select id, username, email from users order by id").fetchall()
        return [_public_user(row) for row in rows]

    def get(self, user_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                "select id, username, email from users where id = %s",
                (user_id,),
            ).fetchone()
        return _public_user(row) if row is not None else None

    def get_by_username(self, username: str) -> dict[str, Any] | None:
        clean_username = username.strip()
        if not clean_username:
            return None
        with connect() as conn:
            row = conn.execute(
                "select id, username, password, email from users where lower(username) = lower(%s)",
                (clean_username,),
            ).fetchone()
        return dict(row) if row is not None else None

    def create(self, username: str, password: str, email: str = "") -> dict[str, Any]:
        clean_username = username.strip()
        clean_password = password.strip()
        clean_email = email.strip()
        if not clean_username:
            raise ValueError("用户名不能为空")
        if not clean_password:
            raise ValueError("密码不能为空")
        if self.get_by_username(clean_username) is not None:
            raise ValueError("用户名已存在")

        with connect() as conn:
            row = conn.execute(
                """
                insert into users (username, password, email)
                values (%s, %s, %s)
                returning id, username, email
                """,
                (clean_username, clean_password, clean_email),
            ).fetchone()
        return _public_user(row)

    def authenticate(self, username: str, password: str) -> dict[str, Any] | None:
        user = self.get_by_username(username)
        if user is None or user.get("password") != password:
            return None
        return _public_user(user)

    def seed_from_json(self, path: Path) -> None:
        raw = _read_json(path)
        if not isinstance(raw, list):
            return
        with connect() as conn:
            for item in raw:
                if not isinstance(item, dict):
                    continue
                username = str(item.get("username", "")).strip()
                password = str(item.get("password", "")).strip()
                if not username or not password:
                    continue
                exists = conn.execute(
                    "select id from users where lower(username) = lower(%s)",
                    (username,),
                ).fetchone()
                if exists is not None:
                    continue
                user_id = _coerce_int(item.get("id"))
                email = str(item.get("email", "")).strip()
                if user_id is not None and user_id > 0:
                    conn.execute(
                        """
                        insert into users (id, username, password, email)
                        values (%s, %s, %s, %s)
                        on conflict do nothing
                        """,
                        (user_id, username, password, email),
                    )
                else:
                    conn.execute(
                        "insert into users (username, password, email) values (%s, %s, %s)",
                        (username, password, email),
                    )
            conn.execute(
                """
                select setval(
                  pg_get_serial_sequence('users', 'id'),
                  greatest((select coalesce(max(id), 1) from users), 1),
                  true
                )
                """
            )


class PostgresCollection:
    def __init__(
        self,
        table: str,
        defaults: dict[str, Any] | None = None,
        unwrap_data: bool = False,
    ) -> None:
        if table not in CONTENT_TABLES:
            raise ValueError(f"unsupported table: {table}")
        self.table = table
        self.defaults = defaults
        self.unwrap_data = unwrap_data

    def list_all(self, user_id: int) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute(
                f"select id, data from {self.table} where user_id = %s order by id",
                (user_id,),
            ).fetchall()
        return [self._row_to_item(row) for row in rows]

    def get(self, user_id: int, item_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                f"select id, data from {self.table} where id = %s and user_id = %s",
                (item_id, user_id),
            ).fetchone()
        return self._row_to_item(row) if row is not None else None

    def create(self, user_id: int, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._shape_item(payload)
        with connect() as conn:
            row = conn.execute(
                f"insert into {self.table} (user_id, data) values (%s, %s) returning id, data",
                (user_id, Jsonb(data)),
            ).fetchone()
            item = self._row_to_item(row)
            self._save_item_data(conn, int(row["id"]), item)
        return item

    def replace(self, user_id: int, item_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._shape_item(payload)
        with connect() as conn:
            row = conn.execute(
                f"""
                update {self.table}
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), item_id, user_id),
            ).fetchone()
            if row is None:
                return None
            item = self._row_to_item(row)
            self._save_item_data(conn, int(row["id"]), item)
        return item

    def patch(self, user_id: int, item_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get(user_id, item_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        data = self._shape_item(patched)
        data["id"] = item_id
        self._ensure_uid(data)
        with connect() as conn:
            row = conn.execute(
                f"""
                update {self.table}
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(self._data_for_storage(data)), item_id, user_id),
            ).fetchone()
        return self._row_to_item(row) if row is not None else None

    def delete(self, user_id: int, item_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                f"delete from {self.table} where id = %s and user_id = %s",
                (item_id, user_id),
            )
        return cursor.rowcount > 0

    def _save_item_data(self, conn: psycopg.Connection, item_id: int, item: dict[str, Any]) -> None:
        conn.execute(
            f"update {self.table} set data = %s, updated_at = now() where id = %s",
            (Jsonb(self._data_for_storage(item)), item_id),
        )

    def _row_to_item(self, row: dict[str, Any]) -> dict[str, Any]:
        item = self._shape_item(dict(row.get("data") or {}))
        item["id"] = int(row["id"])
        self._ensure_uid(item)
        return item

    def _shape_item(self, item: dict[str, Any]) -> dict[str, Any]:
        if self.defaults is None:
            return deepcopy(item)

        source = deepcopy(item)
        if self.unwrap_data and isinstance(source.get("data"), dict):
            source = {"spec": source.get("spec", ""), **source["data"]}

        return {
            key: _coerce_by_default(source[key], default) if key in source else deepcopy(default)
            for key, default in self.defaults.items()
        }

    def _ensure_uid(self, item: dict[str, Any]) -> None:
        if "uid" not in item:
            return
        uid = _coerce_int(item.get("uid"))
        item_id = _coerce_int(item.get("id"))
        if (uid is None or uid <= 0) and item_id is not None:
            item["uid"] = item_id

    def _data_for_storage(self, item: dict[str, Any]) -> dict[str, Any]:
        data = deepcopy(item)
        data.pop("id", None)
        data.pop("created_at", None)
        data.pop("updated_at", None)
        return data


class PostgresLorebookCollection(PostgresCollection):
    def list_entries(self, user_id: int, lorebook_id: int) -> list[dict[str, Any]] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        entries = self._normalize_entries(lorebook.get("entries"))
        return [deepcopy(entry) for _, entry in entries]

    def get_entry(self, user_id: int, lorebook_id: int, entry_id: int) -> dict[str, Any] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        for _, entry in self._normalize_entries(lorebook.get("entries")):
            if self._entry_id(entry) == entry_id:
                return deepcopy(entry)
        return None

    def create_entry(self, user_id: int, lorebook_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        entries = self._normalize_entries(lorebook.get("entries"))
        new_entry = self._prepare_entry_create(payload, entries)
        entries.append((str(self._entry_id(new_entry)), new_entry))
        lorebook["entries"] = {key: entry for key, entry in entries}
        self.replace(user_id, lorebook_id, lorebook)
        return deepcopy(new_entry)

    def replace_entry(
        self,
        user_id: int,
        lorebook_id: int,
        entry_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        return self._mutate_entry(user_id, lorebook_id, payload, "replace", entry_id)

    def patch_entry(
        self,
        user_id: int,
        lorebook_id: int,
        entry_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        return self._mutate_entry(user_id, lorebook_id, payload, "patch", entry_id)

    def delete_entry(self, user_id: int, lorebook_id: int, entry_id: int) -> bool:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return False
        entries = self._normalize_entries(lorebook.get("entries"))
        filtered = [(key, entry) for key, entry in entries if self._entry_id(entry) != entry_id]
        if len(filtered) == len(entries):
            return False
        lorebook["entries"] = {key: entry for key, entry in filtered}
        self.replace(user_id, lorebook_id, lorebook)
        return True

    def _mutate_entry(
        self,
        user_id: int,
        lorebook_id: int,
        payload: dict[str, Any],
        mode: str,
        entry_id: int,
    ) -> dict[str, Any] | None:
        lorebook = self.get(user_id, lorebook_id)
        if lorebook is None:
            return None
        entries = self._normalize_entries(lorebook.get("entries"))
        for index, (key, entry) in enumerate(entries):
            if self._entry_id(entry) != entry_id:
                continue
            if mode == "replace":
                updated = self._prepare_entry_replace(payload, entry_id)
            else:
                updated = self._prepare_entry_patch(entry, payload, entry_id)
            entries[index] = (key, updated)
            lorebook["entries"] = {entry_key: entry_value for entry_key, entry_value in entries}
            self.replace(user_id, lorebook_id, lorebook)
            return deepcopy(updated)
        return None

    def _shape_item(self, item: dict[str, Any]) -> dict[str, Any]:
        shaped = super()._shape_item(item)
        entries = self._normalize_entries(item.get("entries", shaped.get("entries")))
        shaped["entries"] = {key: entry for key, entry in entries}
        return shaped

    def _normalize_entries(self, entries: Any) -> list[tuple[str, dict[str, Any]]]:
        if isinstance(entries, dict):
            source_items = list(entries.items())
        elif isinstance(entries, list):
            source_items = [(str(index + 1), value) for index, value in enumerate(entries)]
        else:
            source_items = []

        normalized: list[tuple[str, dict[str, Any]]] = []
        next_entry_id = self._next_entry_id(source_items)
        for raw_key, raw_entry in source_items:
            if not isinstance(raw_entry, dict):
                continue
            raw_entry_id = self._entry_id(raw_entry)
            raw_uid = _coerce_int(raw_entry.get("uid"))
            key_id = _coerce_int(raw_key)
            entry_id = raw_entry_id if raw_entry_id is not None else raw_uid
            if entry_id is None or entry_id <= 0:
                entry_id = key_id
            if entry_id is None:
                entry_id = next_entry_id
            entry = self._shape_entry(raw_entry)
            entry["id"] = entry_id
            self._ensure_entry_uid(entry, entry_id)
            normalized.append((str(entry_id), entry))
            if entry_id >= next_entry_id:
                next_entry_id = entry_id + 1
        normalized.sort(key=lambda item: self._entry_id(item[1]) or 0)
        return normalized

    def _shape_entry(self, entry: dict[str, Any]) -> dict[str, Any]:
        return {
            key: _coerce_by_default(entry[key], default) if key in entry else deepcopy(default)
            for key, default in ENTRY_DEFAULTS.items()
        }

    def _prepare_entry_create(
        self,
        payload: dict[str, Any],
        entries: list[tuple[str, dict[str, Any]]],
    ) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        entry = self._shape_entry(payload)
        uid = _coerce_int(entry.get("uid"))
        next_entry_id = self._next_entry_id(entries)
        entry_id = uid if uid is not None and uid > 0 else next_entry_id
        entry["id"] = entry_id
        self._ensure_entry_uid(entry, entry_id)
        return entry

    def _prepare_entry_replace(self, payload: dict[str, Any], entry_id: int) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        entry = self._shape_entry(payload)
        entry["id"] = entry_id
        self._ensure_entry_uid(entry, entry_id)
        return entry

    def _prepare_entry_patch(
        self,
        current_entry: dict[str, Any],
        payload: dict[str, Any],
        entry_id: int,
    ) -> dict[str, Any]:
        patched = deepcopy(current_entry)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        entry = self._shape_entry(patched)
        entry["id"] = entry_id
        self._ensure_entry_uid(entry, entry_id)
        return entry

    def _ensure_entry_uid(self, entry: dict[str, Any], entry_id: int) -> None:
        uid = _coerce_int(entry.get("uid"))
        if uid is None or uid <= 0:
            entry["uid"] = entry_id

    def _entry_id(self, entry: dict[str, Any]) -> int | None:
        return _coerce_int(entry.get("id"))

    def _next_entry_id(self, entries: list[tuple[str, dict[str, Any]]]) -> int:
        max_id = 0
        for key, entry in entries:
            if not isinstance(entry, dict):
                continue
            entry_id = self._entry_id(entry)
            if entry_id is None:
                entry_id = _coerce_int(entry.get("uid"))
            if entry_id is None:
                entry_id = _coerce_int(key)
            if entry_id is not None and entry_id > max_id:
                max_id = entry_id
        return max_id + 1


class PostgresStoryCollection:
    def list_all(self, user_id: int) -> list[dict[str, Any]]:
        with connect() as conn:
            rows = conn.execute(
                """
                select id, user_id, data, created_at, updated_at
                from stories
                where user_id = %s
                order by id
                """,
                (user_id,),
            ).fetchall()
            return [self._row_to_story(conn, row) for row in rows]

    def get(self, user_id: int, story_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                """
                select id, user_id, data, created_at, updated_at
                from stories
                where id = %s and user_id = %s
                """,
                (story_id, user_id),
            ).fetchone()
            return self._row_to_story(conn, row) if row is not None else None

    def create(self, user_id: int, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        rounds = payload.get("round", [])
        data = self._story_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                insert into stories (user_id, data)
                values (%s, %s)
                returning id, user_id, data, created_at, updated_at
                """,
                (user_id, Jsonb(data)),
            ).fetchone()
            story_id = int(row["id"])
            for position, round_item in enumerate(self._normalize_rounds(rounds), start=1):
                self._insert_round(conn, user_id, story_id, round_item, position)
            return self._row_to_story(conn, row)

    def replace(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        rounds = payload.get("round", [])
        data = self._story_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                update stories
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, user_id, data, created_at, updated_at
                """,
                (Jsonb(data), story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "delete from story_rounds where story_id = %s and user_id = %s",
                (story_id, user_id),
            )
            for position, round_item in enumerate(self._normalize_rounds(rounds), start=1):
                self._insert_round(conn, user_id, story_id, round_item, position)
            return self._row_to_story(conn, row)

    def patch(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get(user_id, story_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key not in {"id", "created_at", "updated_at"}:
                patched[key] = value
        data = self._story_data_for_storage(patched)
        with connect() as conn:
            row = conn.execute(
                """
                update stories
                set data = %s, updated_at = now()
                where id = %s and user_id = %s
                returning id, user_id, data, created_at, updated_at
                """,
                (Jsonb(data), story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            if "round" in payload:
                conn.execute(
                    "delete from story_rounds where story_id = %s and user_id = %s",
                    (story_id, user_id),
                )
                for position, round_item in enumerate(self._normalize_rounds(payload.get("round", [])), start=1):
                    self._insert_round(conn, user_id, story_id, round_item, position)
            return self._row_to_story(conn, row)

    def delete(self, user_id: int, story_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                "delete from stories where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return cursor.rowcount > 0

    def list_rounds(self, user_id: int, story_id: int) -> list[dict[str, Any]] | None:
        if not self._story_exists(user_id, story_id):
            return None
        with connect() as conn:
            return self._list_rounds(conn, user_id, story_id)

    def get_round(self, user_id: int, story_id: int, round_id: int) -> dict[str, Any] | None:
        with connect() as conn:
            row = conn.execute(
                """
                select id, data
                from story_rounds
                where id = %s and story_id = %s and user_id = %s
                """,
                (round_id, story_id, user_id),
            ).fetchone()
        return self._row_to_round(row) if row is not None else None

    def create_round(self, user_id: int, story_id: int, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not self._story_exists(user_id, story_id):
            return None
        with connect() as conn:
            position = self._next_round_position(conn, user_id, story_id)
            round_item = self._insert_round(conn, user_id, story_id, payload, position)
            conn.execute(
                "update stories set updated_at = now() where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return round_item

    def replace_round(
        self,
        user_id: int,
        story_id: int,
        round_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        data = self._round_data_for_storage(payload)
        with connect() as conn:
            row = conn.execute(
                """
                update story_rounds
                set data = %s, updated_at = now()
                where id = %s and story_id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), round_id, story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "update stories set updated_at = now() where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return self._row_to_round(row)

    def patch_round(
        self,
        user_id: int,
        story_id: int,
        round_id: int,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        current = self.get_round(user_id, story_id, round_id)
        if current is None:
            return None
        patched = deepcopy(current)
        for key, value in payload.items():
            if key != "id":
                patched[key] = value
        data = self._round_data_for_storage(patched)
        with connect() as conn:
            row = conn.execute(
                """
                update story_rounds
                set data = %s, updated_at = now()
                where id = %s and story_id = %s and user_id = %s
                returning id, data
                """,
                (Jsonb(data), round_id, story_id, user_id),
            ).fetchone()
            if row is None:
                return None
            conn.execute(
                "update stories set updated_at = now() where id = %s and user_id = %s",
                (story_id, user_id),
            )
        return self._row_to_round(row)

    def delete_round(self, user_id: int, story_id: int, round_id: int) -> bool:
        with connect() as conn:
            cursor = conn.execute(
                """
                delete from story_rounds
                where id = %s and story_id = %s and user_id = %s
                """,
                (round_id, story_id, user_id),
            )
            deleted = cursor.rowcount > 0
            if deleted:
                conn.execute(
                    "update stories set updated_at = now() where id = %s and user_id = %s",
                    (story_id, user_id),
                )
        return deleted

    def _story_exists(self, user_id: int, story_id: int) -> bool:
        with connect() as conn:
            row = conn.execute(
                "select id from stories where id = %s and user_id = %s",
                (story_id, user_id),
            ).fetchone()
        return row is not None

    def _row_to_story(self, conn: psycopg.Connection, row: dict[str, Any]) -> dict[str, Any]:
        story = dict(row.get("data") or {})
        story["id"] = int(row["id"])
        story["created_at"] = _iso(row.get("created_at")) or _now_iso()
        story["updated_at"] = _iso(row.get("updated_at")) or story["created_at"]
        story["round"] = self._list_rounds(conn, int(row["user_id"]), int(row["id"]))
        return story

    def _list_rounds(self, conn: psycopg.Connection, user_id: int, story_id: int) -> list[dict[str, Any]]:
        rows = conn.execute(
            """
            select id, data
            from story_rounds
            where user_id = %s and story_id = %s
            order by position, id
            """,
            (user_id, story_id),
        ).fetchall()
        return [self._row_to_round(row) for row in rows]

    def _insert_round(
        self,
        conn: psycopg.Connection,
        user_id: int,
        story_id: int,
        payload: dict[str, Any],
        position: int,
    ) -> dict[str, Any]:
        data = self._round_data_for_storage(payload)
        row = conn.execute(
            """
            insert into story_rounds (user_id, story_id, position, data)
            values (%s, %s, %s, %s)
            returning id, data
            """,
            (user_id, story_id, position, Jsonb(data)),
        ).fetchone()
        return self._row_to_round(row)

    def _next_round_position(self, conn: psycopg.Connection, user_id: int, story_id: int) -> int:
        row = conn.execute(
            """
            select coalesce(max(position), 0) + 1 as next_position
            from story_rounds
            where user_id = %s and story_id = %s
            """,
            (user_id, story_id),
        ).fetchone()
        return int(row["next_position"])

    def _story_data_for_storage(self, payload: dict[str, Any]) -> dict[str, Any]:
        data = deepcopy(payload)
        for key in ("id", "created_at", "updated_at", "round"):
            data.pop(key, None)
        return data

    def _round_data_for_storage(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise TypeError("payload must be a JSON object")
        round_item = deepcopy(payload)
        round_item.pop("id", None)
        self._normalize_round_shape(round_item)
        return round_item

    def _row_to_round(self, row: dict[str, Any]) -> dict[str, Any]:
        round_item = dict(row.get("data") or {})
        round_item["id"] = int(row["id"])
        self._normalize_round_shape(round_item)
        return round_item

    def _normalize_rounds(self, rounds: Any) -> list[dict[str, Any]]:
        if not isinstance(rounds, list):
            return []
        normalized = []
        next_id = self._next_round_id(rounds)
        for raw_round in rounds:
            if not isinstance(raw_round, dict):
                continue
            round_item = deepcopy(raw_round)
            round_id = _coerce_int(round_item.get("id"))
            if round_id is None or round_id <= 0:
                round_item["id"] = next_id
                next_id += 1
            else:
                round_item["id"] = round_id
            self._normalize_round_shape(round_item)
            normalized.append(round_item)
        return normalized

    def _next_round_id(self, rounds: Any) -> int:
        if not isinstance(rounds, list):
            return 1
        max_id = 0
        for round_item in rounds:
            if not isinstance(round_item, dict):
                continue
            round_id = _coerce_int(round_item.get("id"))
            if round_id is not None and round_id > max_id:
                max_id = round_id
        return max_id + 1

    def _normalize_round_shape(self, round_item: dict[str, Any]) -> None:
        round_item.setdefault("scene", "")
        round_item.setdefault("narration", "")
        first = round_item.get("first")
        round_item["first"] = first if first in {"role1", "role2"} else "role1"
        round_item.setdefault("next_scene", "")
        round_item.setdefault("next_narration", "")
        next_first = round_item.get("next_first")
        round_item["next_first"] = next_first if next_first in {"role1", "role2"} else "role1"
        for role_key in ("role1", "role2"):
            action_key = f"{role_key}_action"
            dialogue_key = f"{role_key}_dialogue"
            output_key = f"{role_key}_output"
            round_item.setdefault(action_key, "")
            round_item.setdefault(dialogue_key, "")
            if not round_item.get(output_key):
                round_item[output_key] = _format_output(
                    round_item.get(action_key, ""),
                    round_item.get(dialogue_key, ""),
                )
            elif not round_item.get(action_key) and not round_item.get(dialogue_key):
                round_item[output_key] = str(round_item.get(output_key, ""))


def seed_legacy_json_data(
    data_dir: Path,
    user_store: PostgresUserStore,
    role_store: PostgresCollection,
    preset_store: PostgresCollection,
    entry_store: PostgresCollection,
    lorebook_store: PostgresLorebookCollection,
    story_store: PostgresStoryCollection,
) -> None:
    user_store.seed_from_json(data_dir / "users.json")
    users = user_store.list_all()
    if not users:
        return
    owner_id = int(users[0]["id"])

    _seed_collection(role_store, owner_id, data_dir / "roles.json")
    _seed_collection(preset_store, owner_id, data_dir / "preset.json")
    _seed_collection(entry_store, owner_id, data_dir / "entries.json")
    _seed_collection(lorebook_store, owner_id, data_dir / "lorebooks.json")
    _seed_stories(story_store, owner_id, data_dir / "stories")


def _seed_collection(store: PostgresCollection, user_id: int, path: Path) -> None:
    if store.list_all(user_id):
        return
    raw = _read_json(path)
    if not isinstance(raw, list):
        return
    for item in raw:
        if isinstance(item, dict):
            store.create(user_id, item)


def _seed_stories(store: PostgresStoryCollection, user_id: int, stories_dir: Path) -> None:
    if store.list_all(user_id) or not stories_dir.exists():
        return
    for file_path in sorted(stories_dir.glob("story_*.json")):
        story = _read_json(file_path)
        if isinstance(story, dict):
            store.create(user_id, story)
