
from __future__ import annotations

from .base import connect

SCHEMA_SQL = """
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null,
  password text not null,
  email text not null default '',
  role text not null default 'normal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table users add column if not exists role text not null default 'normal';

create unique index if not exists users_username_lower_uidx on users (lower(username));

insert into users (username, password, email, role)
select 'super_admin', 'super_admin123', 'super@xtplay.com', 'super_admin'
where not exists (select 1 from users where lower(username) = 'super_admin');
update users set role = 'admin' where username = 'admin' and role = 'normal';

create table if not exists roles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists presets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lorebooks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists stories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists story_rounds (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  story_id bigint not null references stories(id) on delete cascade,
  position integer not null default 0,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists prompts (
  key text primary key,
  title text not null default '',
  category text not null default '',
  description text not null default '',
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists roles_user_id_idx on roles (user_id);
create index if not exists presets_user_id_idx on presets (user_id);
create index if not exists entries_user_id_idx on entries (user_id);
create index if not exists lorebooks_user_id_idx on lorebooks (user_id);
create index if not exists stories_user_id_idx on stories (user_id);
create index if not exists story_rounds_user_id_idx on story_rounds (user_id);
create index if not exists story_rounds_story_id_idx on story_rounds (story_id);
create index if not exists story_rounds_story_position_idx on story_rounds (story_id, position, id);
create index if not exists prompts_category_idx on prompts (category);

create table if not exists story_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  story_id bigint not null references stories(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists session_rounds (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  session_id bigint not null references story_sessions(id) on delete cascade,
  position integer not null default 0,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists story_sessions_user_id_idx on story_sessions (user_id);
create index if not exists story_sessions_story_id_idx on story_sessions (story_id);
create index if not exists session_rounds_user_id_idx on session_rounds (user_id);
create index if not exists session_rounds_session_id_idx on session_rounds (session_id);
create index if not exists session_rounds_session_position_idx on session_rounds (session_id, position, id);
"""


def init_db() -> None:
    with connect() as conn:
        for statement in SCHEMA_SQL.split(";"):
            sql = statement.strip()
            if sql:
                conn.execute(sql)

