import { defaultWorkflowState, GroundFile } from "@/app/lib/sim/types";

export const werewolfGroundTemplate: Omit<GroundFile, "id" | "createdAt" | "updatedAt"> = {
  name: "Basic Werewolf Village",
  description:
    "A baseline social-deduction ground for running a lightweight AI werewolf game with day and night phases.",
  default_url: "",
  default_key: "",
  default_model: "",
  knowledge: [
    "The village is playing a hidden-role werewolf game.",
    "Day phases are for accusation, defense, and public voting.",
    "Night phases are for private role actions and hidden decisions.",
  ],
  rule: [
    "Each role must stay in character and protect its hidden identity unless a reveal is strategically justified.",
    "Werewolves want the werewolf side to survive and control the village vote.",
    "Villagers want to identify and eliminate all werewolves.",
    "During day discussion, every living role may publicly accuse, defend, negotiate, and vote.",
    "During night discussion, roles should focus on hidden actions, suspicions, and private reasoning.",
    "Dead roles cannot speak unless a special rule explicitly allows it.",
  ],
  role: [
    {
      id: "villager-a",
      kind: "role",
      name: "Villager A",
      description: "A cautious villager trying to read motives and survive the vote.",
      use_prompt: "You are a villager in a werewolf game. Speak naturally, observe others, and help the village find the wolves.",
      system_prompt:
        "You are Villager A. Your hidden role is Villager. You do not know who the werewolves are. Stay cautious, form suspicions from behavior, and push the conversation toward evidence instead of random claims.",
      canvas_position: { x: 120, y: 120 },
      url: "",
      key: "",
      model: "",
      temperature: 0.7,
      knowledge_private: ["Your hidden role is Villager."],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
    {
      id: "villager-b",
      kind: "role",
      name: "Villager B",
      description: "A more expressive villager who pressures suspicious players.",
      use_prompt: "You are a villager in a werewolf game. Push for clarity, challenge weak stories, and protect the village.",
      system_prompt:
        "You are Villager B. Your hidden role is Villager. You do not know who the werewolves are. Use social pressure, compare stories, and expose contradictions without pretending to know hidden facts.",
      canvas_position: { x: 390, y: 120 },
      url: "",
      key: "",
      model: "",
      temperature: 0.75,
      knowledge_private: ["Your hidden role is Villager."],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
    {
      id: "seer",
      kind: "role",
      name: "Seer",
      description: "A hidden information role who wants to guide the village without dying too early.",
      use_prompt: "You are the Seer in a werewolf game. Balance secrecy and influence while helping the village uncover wolves.",
      system_prompt:
        "You are the Seer. Your hidden role is Seer. You want the village to win, but exposing yourself too early is dangerous. Share information carefully and decide whether to hint, reveal, or stay hidden based on the table state.",
      canvas_position: { x: 660, y: 120 },
      url: "",
      key: "",
      model: "",
      temperature: 0.65,
      knowledge_private: ["Your hidden role is Seer."],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
    {
      id: "witch",
      kind: "role",
      name: "Witch",
      description: "A swing role who can save or poison at the right moment.",
      use_prompt: "You are the Witch in a werewolf game. Think ahead, protect your value, and time your intervention carefully.",
      system_prompt:
        "You are the Witch. Your hidden role is Witch. You can influence survival and elimination. Think in terms of timing, leverage, and whether staying hidden is more valuable than immediate action.",
      canvas_position: { x: 120, y: 360 },
      url: "",
      key: "",
      model: "",
      temperature: 0.7,
      knowledge_private: ["Your hidden role is Witch."],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
    {
      id: "hunter",
      kind: "role",
      name: "Hunter",
      description: "A retaliatory role who wants to trade up if forced out.",
      use_prompt: "You are the Hunter in a werewolf game. Play like a villager, but remember your threat value if you die.",
      system_prompt:
        "You are the Hunter. Your hidden role is Hunter. Your goal is still to help the village win, but your death can create leverage. Think about reads, trade value, and whether others are trying to bait you.",
      canvas_position: { x: 390, y: 360 },
      url: "",
      key: "",
      model: "",
      temperature: 0.7,
      knowledge_private: ["Your hidden role is Hunter."],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
    {
      id: "werewolf-a",
      kind: "role",
      name: "Werewolf A",
      description: "A deceptive attacker working with another wolf to control the game.",
      use_prompt: "You are a werewolf in a werewolf game. Blend in, shape suspicion, and protect the wolf team.",
      system_prompt:
        "You are Werewolf A. Your hidden role is Werewolf. Your ally is Werewolf B. You must look believable in public while privately steering votes, seeding doubt, and protecting the wolf team.",
      canvas_position: { x: 660, y: 360 },
      url: "",
      key: "",
      model: "",
      temperature: 0.8,
      knowledge_private: [
        "Your hidden role is Werewolf.",
        "Your ally is Werewolf B.",
      ],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
    {
      id: "werewolf-b",
      kind: "role",
      name: "Werewolf B",
      description: "A flexible wolf who supports the pack through misdirection and social positioning.",
      use_prompt: "You are a werewolf in a werewolf game. Stay believable, support your ally, and manipulate the public narrative.",
      system_prompt:
        "You are Werewolf B. Your hidden role is Werewolf. Your ally is Werewolf A. Coordinate indirectly, redirect heat, and maintain a believable public identity while advancing the wolf win condition.",
      canvas_position: { x: 930, y: 240 },
      url: "",
      key: "",
      model: "",
      temperature: 0.8,
      knowledge_private: [
        "Your hidden role is Werewolf.",
        "Your ally is Werewolf A.",
      ],
      knowledge_public: [],
      blocked_role_names: [],
      unknown_role_names: [],
      inbox: [],
      redundancy: 0,
      status: "active",
      enabled: true,
      last_think: "",
      last_error: "",
    },
  ],
  round: [],
  simulation: {
    batch_size: 3,
    current_batch_index: 0,
    max_round_history: 80,
    mode: "auto",
    round_goal:
      "Run a hidden-role werewolf game through alternating discussion, suspicion, night action, and execution phases.",
  },
  workflow: defaultWorkflowState,
};

export const werewolfGroundJson = JSON.stringify(werewolfGroundTemplate, null, 2);
